services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - bookpgdata:/var/lib/postgresql/data

volumes:
  bookpgdata:
    